### ISSUE TITLE
working questions about the plugin

### ISSUE THREAD

**Issue by Dan11lkaa** [zakhij/obsidian-activity-heatmap#17]
How are counted words and file size? For example, counting the number of words in my opinion does not work correctly, because when deleting some printed text and writing a new text in its place, the words from the previous text and also from the new text will be counted, although by idea this should not happen, because the words of the deleted text have already been counted at the time of its writing, and it turns out after its change is counted words from this text for the second time, and also counted from the new text. And it turns out that the statistics is incorrect. I don't understand what exactly this metric measures "file size". number of characters, file bytes or what exactly? I would like to see a correctly working product in the near future, as well as comments on these questions.

**Comment by zakhij** [comment]
1) Deleting a word counts as activity in the same way that adding a word does. So yes, if you re-write some text, it will consider both the deletion and addition as activity. You make a good point though. Do you think it would be better to only capture additions? And if so, what makes sense for migration to future versions?
2) Yes, file size = bytes (https://docs.obsidian.md/Reference/TypeScript+API/FileStats/size). PR #2  should make this clearer in the tooltip (haven't had time to get to it, been focusing on more pressing backend issues)

**Comment by Dan11lkaa** [comment]
Yes, I believe that only additions of words to as activity should be recorded. Deletions should be ignored. Well, think about it, yesterday you wrote some part of the article in Obsidian, sootvetstvenno spent some time, tomorrow you did not like it at all and you decide to delete it and then write another. You have done completely different time-consuming and time-consuming cases (wrote a text or deleted it), but it counts as one and the same. Logically, I could just write a text in a loop and then delete it the next day, and the activity would be the same, but that's not right. Also I would like to heatmap itself was bigger, it is currently not very convenient it, because small, I would also like more metrics, such as the amount of time spent in obsidian - would also be a bomb. And also for heatmap should be made for different time intervals (week, month, year) as always look at the year when you need to know only for a short period of time - this is also not very convenient. I think that you have understood where you need to move, but in the near future it is necessary to fix the logic of activity, which I wrote earlier, as it is a very important nuance, which so far makes me think on the light of using your plugin.

**Comment by zakhij** [comment]
I think that makes sense. But what about users that are already using the plugin? If the user upgrades to the newest version with  a modified word count calculation method, then we are now comparing two different types of values. What do you suggest we do here?

**Comment by Dan11lkaa** [comment]
Will you take my preferences into account? if yes, then approximately when should I expect an update taking these aspects into account? I just need to understand whether I should wait for your update or whether it would be better to implement something similar myself, taking into account all your shortcomings?

**Comment by zakhij** [comment]
I encourage you to make individual issues on these! Not sure when I'd be able to work on them, but feel free to fork and contribute as well.
