### ISSUE TITLE
Cannot read properties of undefined (reading 'fileSize') in Obsidian 1.6.7

### ISSUE THREAD

**Issue by dsaperov** [zakhij/obsidian-activity-heatmap#3]
Hi! I am on Obsidian 1.6.7 and I can't make the plugin work.

There's a message in the console:
```
plugin:activity-heatmap:13 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'fileSize')
    at Yp.removeFileMetrics (plugin:activity-heatmap:13:60931)
    at eval (plugin:activity-heatmap:26:5445)
    at e.tryTrigger (app.js:1:723190)
    at e.trigger (app.js:1:723123)
    at t.trigger (app.js:1:741273)
    at t.onChange (app.js:1:731654)
    at e.trigger (app.js:1:549102)
    at e.removeFile (app.js:1:549915)
    at e.<anonymous> (app.js:1:549020)
    at app.js:1:237138
```

When I try to use activity heatmap command the modal window is being opened but there's no heatmap.
![image](https://github.com/user-attachments/assets/0b974b81-cfcd-498f-9a04-2d2979d8985a)

I like the idea of your plugin so would be very glad if you can fix this issue. Thanks!

**Comment by zakhij** [comment]
Thank you for the feedback - I made changes last week directly on master that mostly address this issue, and the new version (1.0.4) reflects that. The plugin now works for first-time users. And in your case, if want, you can update the plugin and delete the 'data.json' file in the core plugin files (vault > .obsidian > activity-heatmap > data.json) to get the plugin to work as intended. Or, wait until I come out with a more complete fix, probably later this week

**Comment by dsaperov** [comment]
I updated the plugin, deleted `data.json` and now it works fine. Thanks!
